name: E2E Testing with CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main, master]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    services:
      postgres-e2e:
        image: postgres:15.3
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: db_e2e
          POSTGRES_USER: e2e
          POSTGRES_PASSWORD: e2e123
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0

      - name: Install Dependencies for CI
        run: npm ci

      - name: Run Unit Test
        run: npm run test:e2e:ci
        env:
          PORT: 3001
          NODE_ENV: "ci"
          PUBLIC_PATH: "public"
          JWT_SEED: "3D7mQJx8cAtdG7VZnrS25Wp2C4vqKyYJ"
          POSTGRES_URL: "postgresql://e2e:e2e123@postgres-e2e:5432/db_e2e"
